server:
  port: 8088
  servlet:
    path: /
logging: 
  level: 
    com.leyou:  debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.27.223.38:3306/leyou
    username: root
    password: root
mybatis: 
  type-aliases-package: com.leyou.pojo
    